### ISSUE TITLE
I got this error

### ISSUE THREAD

**Issue by ghost** [hrshadhin/school-website#2]
Error:

```
➜  school-website git:(master) ✗ npm run dev                                                

> sms-frontend@1.0.0 dev
> NODE_ENV=development node_modules/.bin/webpack --mode development

clean-webpack-plugin: /Users/jonathan/Documents/Website/Wirsberg/school-website/frontend has been removed.
Hash: 3b85e2a122bf06251fba
Version: webpack 4.46.0
Time: 2262ms
Built at: 21/07/2021 15:57:57
                                                             Asset        Size  Chunks             Chunk Names
                                                  flags/1x1/bd.svg   195 bytes          [emitted]  
                                                  flags/1x1/gb.svg   792 bytes          [emitted]  
                                                  flags/1x1/in.svg    1.07 KiB          [emitted]  
                                                  flags/4x3/bd.svg   193 bytes          [emitted]  
                                                  flags/4x3/gb.svg   834 bytes          [emitted]  
                                                  flags/4x3/in.svg    1.05 KiB          [emitted]  
                                                fonts/flaticon.eot    9.22 KiB          [emitted]  
                                                fonts/flaticon.svg     103 KiB          [emitted]  
                                                fonts/flaticon.ttf    9.06 KiB          [emitted]  
                                               fonts/flaticon.woff    6.05 KiB          [emitted]  
                                 fonts/fontawesome-webfont862f.eot    70.8 KiB          [emitted]  
                                 fonts/fontawesome-webfont862f.svg     248 KiB          [emitted]  
                                 fonts/fontawesome-webfont862f.ttf     138 KiB          [emitted]  
                                fonts/fontawesome-webfont862f.woff    81.8 KiB          [emitted]  
                                 fonts/fontawesome-webfontd41d.eot    70.8 KiB          [emitted]  
                                                fonts/sms-font.eot     2.3 KiB          [emitted]  
                                                fonts/sms-font.svg    2.71 KiB          [emitted]  
                                                fonts/sms-font.ttf    2.14 KiB          [emitted]  
                                               fonts/sms-font.woff    1.58 KiB          [emitted]  
                                             img/Quotes_symbol.png    7.43 KiB          [emitted]  
                                          img/fancybox_loading.gif    6.41 KiB          [emitted]  
                                       img/fancybox_loading@2x.gif    13.7 KiB          [emitted]  
                                          img/fancybox_overlay.png  1000 bytes          [emitted]  
                                           img/fancybox_sprite.png    1.33 KiB          [emitted]  
                                        img/fancybox_sprite@2x.png     6.4 KiB          [emitted]  
                                                   img/favicon.png    3.36 KiB          [emitted]  
                                                  img/headerbg.jpg     367 KiB          [emitted]  
                                                      img/logo.png    6.03 KiB          [emitted]  
                                                   img/logo@2x.png    12.5 KiB          [emitted]  
                                                  img/parallax.png    46.4 KiB          [emitted]  
                                        img/parallax_pattern-1.png    11.1 KiB          [emitted]  
                                          img/parallax_pattern.png    28.8 KiB          [emitted]  
                                                   img/pattern.png     1.8 KiB          [emitted]  
                                                        js/libs.js     954 KiB    libs  [emitted]  libs
                                    rs-plugin/assets/coloredbg.png   184 bytes          [emitted]  
                                     rs-plugin/assets/gridtile.png   933 bytes          [emitted]  
                                 rs-plugin/assets/gridtile_3x3.png   938 bytes          [emitted]  
                           rs-plugin/assets/gridtile_3x3_white.png   935 bytes          [emitted]  
                               rs-plugin/assets/gridtile_white.png   931 bytes          [emitted]  
                                       rs-plugin/assets/loader.gif    2.49 KiB          [emitted]  
                                     rs-plugin/css/closedhand.html   326 bytes          [emitted]  
                                          rs-plugin/css/layers.css      87 KiB          [emitted]  
                                      rs-plugin/css/navigation.css    58.2 KiB          [emitted]  
                                       rs-plugin/css/openhand.html   326 bytes          [emitted]  
                                        rs-plugin/css/settings.css    34.4 KiB          [emitted]  
                         rs-plugin/fonts/revicons/revicons90c6.eot    11.9 KiB          [emitted]  
                         rs-plugin/fonts/revicons/revicons90c6.svg    13.4 KiB          [emitted]  
                         rs-plugin/fonts/revicons/revicons90c6.ttf    11.7 KiB          [emitted]  
                        rs-plugin/fonts/revicons/revicons90c6.woff    7.36 KiB          [emitted]  
       rs-plugin/js/extensions/revolution.extension.actions.min.js    4.59 KiB          [emitted]  
       rs-plugin/js/extensions/revolution.extension.kenburn.min.js    3.05 KiB          [emitted]  
rs-plugin/js/extensions/revolution.extension.layeranimation.min.js      51 KiB          [emitted]  
     rs-plugin/js/extensions/revolution.extension.migration.min.js    5.94 KiB          [emitted]  
    rs-plugin/js/extensions/revolution.extension.navigation.min.js    22.4 KiB          [emitted]  
      rs-plugin/js/extensions/revolution.extension.parallax.min.js    7.77 KiB          [emitted]  
    rs-plugin/js/extensions/revolution.extension.slideanims.min.js    27.5 KiB          [emitted]  
         rs-plugin/js/extensions/revolution.extension.video.min.js    17.2 KiB          [emitted]  
                  rs-plugin/js/jquery.themepunch.revolution.min.js    45.3 KiB          [emitted]  
                       rs-plugin/js/jquery.themepunch.tools.min.js     102 KiB          [emitted]  
                                         uploads/570x380-img-1.jpg    8.63 KiB          [emitted]  
                                         uploads/570x380-img-2.jpg    12.7 KiB          [emitted]  
                                           uploads/83x83-img-1.jpg    1.93 KiB          [emitted]  
                                           uploads/83x83-img-2.jpg    2.04 KiB          [emitted]  
                                           uploads/94x94-img-1.jpg    1.98 KiB          [emitted]  
                                   uploads/class/370x280-img-1.jpg     8.8 KiB          [emitted]  
                                   uploads/class/370x280-img-2.jpg    8.85 KiB          [emitted]  
                                   uploads/class/370x280-img-3.jpg    8.43 KiB          [emitted]  
                                   uploads/class/870x460-img-1.jpg    25.1 KiB          [emitted]  
                                uploads/class/870x460-img-1@2x.jpg      17 KiB          [emitted]  
                                 uploads/events/1170x580-img-1.jpg     154 KiB          [emitted]  
                                 uploads/events/1170x580-img-2.jpg     157 KiB          [emitted]  
                                 uploads/events/1170x580-img-3.jpg    78.1 KiB          [emitted]  
                                  uploads/events/370x270-img-5.jpg    7.17 KiB          [emitted]  
                               uploads/events/370x270-img-5@2x.jpg      17 KiB          [emitted]  
                                             uploads/gallery/1.jpg     9.2 KiB          [emitted]  
                                            uploads/gallery/12.jpg      17 KiB          [emitted]  
                                             uploads/gallery/2.jpg     9.1 KiB          [emitted]  
                                            uploads/gallery/22.jpg    16.4 KiB          [emitted]  
                                             uploads/gallery/3.jpg    8.73 KiB          [emitted]  
                                            uploads/gallery/32.jpg    17.4 KiB          [emitted]  
                                             uploads/gallery/4.jpg    4.33 KiB          [emitted]  
                                            uploads/gallery/42.jpg    8.63 KiB          [emitted]  
                                             uploads/gallery/5.jpg    6.01 KiB          [emitted]  
                                            uploads/gallery/52.jpg    12.7 KiB          [emitted]  
                                             uploads/gallery/6.jpg    6.67 KiB          [emitted]  
                                            uploads/gallery/62.jpg    15.5 KiB          [emitted]  
                                       uploads/slider/slider-1.jpg    17.4 KiB          [emitted]  
                                       uploads/slider/slider-2.jpg      17 KiB          [emitted]  
                                       uploads/slider/slider-3.jpg    16.4 KiB          [emitted]  
                                       uploads/slider/slider-4.jpg    15.5 KiB          [emitted]  
                                 uploads/teacher/210x220-img-1.jpg    3.24 KiB          [emitted]  
                                 uploads/teacher/210x220-img-2.jpg    4.04 KiB          [emitted]  
                                 uploads/teacher/210x220-img-3.jpg    3.46 KiB          [emitted]  
                                   uploads/teacher/60x60-img-1.jpg     1.8 KiB          [emitted]  
Entrypoint libs = js/libs.js
[0] multi ./src/js/libs.js ./src/sass/libs.scss 40 bytes {libs} [built]
[./node_modules/css-loader/index.js?url=false!./node_modules/sass-loader/dist/cjs.js!./src/sass/libs.scss] ./node_modules/css-loader?url=false!./node_modules/sass-loader/dist/cjs.js!./src/sass/libs.scss 414 bytes [built] [failed] [1 error]
[./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {libs} [built]
[./src/js/libs.js] 495 bytes {libs} [built]
[./src/libs/TweenMax.min.js] 99.6 KiB {libs} [built]
[./src/libs/jquery-ui.min.js] 223 KiB {libs} [built]
[./src/libs/jquery.fancybox-media.js] 5.18 KiB {libs} [built]
[./src/libs/jquery.fancybox.pack.js] 22.6 KiB {libs} [built]
[./src/libs/jquery.form.min.js] 14.2 KiB {libs} [built]
[./src/libs/jquery.isotope.min.js] 15.7 KiB {libs} [built]
[./src/libs/jquery.validate.min.js] 20.3 KiB {libs} [built]
[./src/libs/main.js] 49.9 KiB {libs} [built]
[./src/libs/owl.carousel.min.js] 14.7 KiB {libs} [built]
[./src/libs/retina.min.js] 2.51 KiB {libs} [built]
[./src/libs/select2.js] 129 KiB {libs} [built]
    + 4 hidden modules

ERROR in ./src/sass/libs.scss
Module build failed (from ./node_modules/css-loader/index.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Node Sass version 6.0.1 is incompatible with ^4.0.0.
    at getRenderFuncFromSassImpl (/Users/jonathan/Documents/Website/Wirsberg/school-website/node_modules/sass-loader/dist/index.js:165:13)
    at Object.loader (/Users/jonathan/Documents/Website/Wirsberg/school-website/node_modules/sass-loader/dist/index.js:79:18)
    at /Users/jonathan/Documents/Website/Wirsberg/school-website/node_modules/webpack/lib/NormalModule.js:316:20
    at /Users/jonathan/Documents/Website/Wirsberg/school-website/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/jonathan/Documents/Website/Wirsberg/school-website/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at runSyncOrAsync (/Users/jonathan/Documents/Website/Wirsberg/school-website/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/Users/jonathan/Documents/Website/Wirsberg/school-website/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at /Users/jonathan/Documents/Website/Wirsberg/school-website/node_modules/loader-runner/lib/LoaderRunner.js:205:4
    at /Users/jonathan/Documents/Website/Wirsberg/school-website/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:85:15
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
 @ ./src/sass/libs.scss

ERROR in ./src/sass/libs.scss (./node_modules/css-loader?url=false!./node_modules/sass-loader/dist/cjs.js!./src/sass/libs.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Node Sass version 6.0.1 is incompatible with ^4.0.0.
    at getRenderFuncFromSassImpl (/Users/jonathan/Documents/Website/Wirsberg/school-website/node_modules/sass-loader/dist/index.js:165:13)
    at Object.loader (/Users/jonathan/Documents/Website/Wirsberg/school-website/node_modules/sass-loader/dist/index.js:79:18)
 @ ./src/sass/libs.scss 2:14-130
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js?url=false!node_modules/sass-loader/dist/cjs.js!src/sass/libs.scss:
    Entrypoint undefined = extract-text-webpack-plugin-output-filename
    [./node_modules/css-loader/index.js?url=false!./node_modules/sass-loader/dist/cjs.js!./src/sass/libs.scss] ./node_modules/css-loader?url=false!./node_modules/sass-loader/dist/cjs.js!./src/sass/libs.scss 414 bytes {0} [built] [failed] [1 error]
    
    ERROR in ./src/sass/libs.scss (./node_modules/css-loader?url=false!./node_modules/sass-loader/dist/cjs.js!./src/sass/libs.scss)
    Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
    Error: Node Sass version 6.0.1 is incompatible with ^4.0.0.
        at getRenderFuncFromSassImpl (/Users/jonathan/Documents/Website/Wirsberg/school-website/node_modules/sass-loader/dist/index.js:165:13)
        at Object.loader (/Users/jonathan/Documents/Website/Wirsberg/school-website/node_modules/sass-loader/dist/index.js:79:18)
```

**Comment by chankitsaini** [comment]
@hrshadhin I go this too, tried on different platforms like apannel, netlify, vps and vercel but all throws the same error.

**Comment by hrshadhin** [comment]
as the error shows ` Error: Node Sass version 6.0.1 is incompatible with ^4.0.0.`. Please try this, if issue persist share your environment details like node,npm,os version.
